# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl:             ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url:                 "https://delta-diy-mri.github.io/"


full:                false
# The ability to use custom themes.
style:
  theme:             "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics:  "UA-92880122-2"

# Let people connect & engage with you through social media.
social:
  twitter_handle:    "DIY_MRI"
  facebook_page:     "https://www.facebook.com/diy.mri"
  github_org:        "delta-diy-mri"
  LinkedIn:          "https://www.linkedin.com/groups/14663170/"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:             "DIY-MRI | 16-18 September 2026"
  description:       "3-day workshop to learn, build and scan on a low-field MRI from sratch"
  image:             "https://github.com/delta-diy-mri/delta-diy-mri.github.io/blob/main/images/DELTA%20LOGO_black%20background.tif"

organiser:
  name:              "LAMRI"
  full_name:         "Geethanath Laboratory for Accessible MRI, Johns Hopkins University"
  site:              "https://imr-framework.github.io/"

# Event information.
event:
  name:              "DIY MRI workshop"
  name_short:        "DIY MRI"
  description:       "Three day workshop to learn, build and scan on a low-field MRI from scratch"
  start_date:        "2026-09-16"
  end_date:          "2026-09-18"
  date:              "16-18 September 2026"
  location:          "Johns Hopkins University, Baltimore, Maryland, USA"
  logosrc:           "images/diy-mri-logo.png"
  logoalt:           "DIY-MRI Logo"

  trust_badge:
    year:            "2026"  # season year
    region:          "na"    # "na" or "eu"
    color:           "white" # "white", "black", "gray", "red", "blue" or "yellow"

  social:
    # - logo:          "images/fb_logo.png"
    #   text:          "Facebook event"
    #   link:          "https://www.facebook.com/events/"
    # - logo:          "images/twitter_logo.png"
    #   text:          "Twitter"
    #   link:          "https://x.com/SG_MRI4all"
    # - logo:          "images/twitter_logo.png"
    #   text:          "Instagram"
    #   link:          "https://x.com/SG_MRI4all"
    - logo:          "images/Linkedin_logo.png"
      text:          "Linkedin"
      link:          "https://www.linkedin.com/groups/14663170/"

  hero:
    my_mlh:
      text:          "Register with MyMlh, too"
      client_id:     "87fceece377ceb70f339e440591e889e918c1d421bd986ff7b58ca3ea9ee1d30"
      redirect_uri:  "delta-diy-mri.github.io"

    # links:
    #   - text:        "Sponsor"
    #     href:        "mailto:sairam.geethanath@jhu.edu"

  about:
    description:     >
      DIY-MRI is a three day workshop at Johns Hopkins University in September.{::nomarkdown}<br />{:/}
      It'll bring together participants for fun-filled three days of learning, building and scanning.{::nomarkdown}<br />{:/}

  workshops:
      - name: "Introduction to 3D printing"
        time: "16th September, 12.00 - 13.00"
        level: "No prior experience required."
        description: "Do you want to learn the basics of CAD designing and printing? We got your covered  -- to design and print your first 3D figurine!"
      - name: "GitHub fundamentals"
        time: "16th September, 12.00 - 13.00"
        level: "Entry level, no prior experience required."
        description: "We will help you get started with creating your profile, creating a repository and pushing code to your GitHub repository."
      
  # Info Sections - will use this section for speakers and mentors
  principals:
    # tier1 is top, anycont is bottom (refer to sponsorship packages)
    speakers:
      - image:       "images/ZB.png"
        name:        "Dr. Zaver Bhujwalla"
        url:         "https://profiles.hopkinsmedicine.org/provider/zaver-m-bhujwalla/2777914"

      - image:       "images/PVZ.png"
        name:        "Dr. Peter Van Zijl"
        url:         "https://www.kennedykrieger.org/patient-care/faculty-staff/peter-van-zijl"

      - image:       "images/JTV.png" 
        name:        "Dr. Thomas Vaughan Jr."
        url:         "https://www.engineering.columbia.edu/faculty-staff/directory/j-thomas-tommy-vaughan-jr"

      - image:        "images/MM.png"
        name:        "Dr. Michael McMahon"
        url:         "https://profiles.hopkinsmedicine.org/provider/michael-t-mc-mahon/2777458"    

      - image:       "images/TC.png"
        name:        "Dr. Todd Constable"
        url:         "https://medicine.yale.edu/profile/todd-constable/" 

      - image:       "images/HL.png"
        name:        "Dr. Hanzhang Lu"
        url:         "https://profiles.hopkinsmedicine.org/provider/hanzhang-lu/2777482"

      - image:       "images/AW.png"
        name:        "Dr. Andrew Webb"
        url:         "https://www.universiteitleiden.nl/en/staffmembers/andrew-webb#tab-1"

      - image:       "images/PB.png"
        name:        "Dr. Peter Barker"
        url:         "https://profiles.hopkinsmedicine.org/provider/peter-b-barker/2777516"  

    leaders:
      - image:       "images/IEO.png"
        team:        "Magnet"
        name:        "Mr. Ivan Etoku Oiye"
        url:         "https://scholar.google.com/citations?user=A7HuxwcAAAAJ&hl=en&oi=ao"

      - image:       "images/CS.png"
        team:        "RF coils"
        name:        "Dr. Charlotte Sappo"
        url:         "https://scholar.google.com/citations?hl=en&user=ND6nPMAAAAAJ"

      - image:       "images/ST.png"
        team:        "Gradient coils"
        name:        "Dr. Sebastian Theilenberg"
        url:         "https://scholar.google.com/citations?hl=en&user=6KAS88gAAAAJ"

      - image:       "images/SG.png"
        team:        "Data acquisition"
        name:        "Dr. Sairam Geethanath"
        url:         "https://profiles.hopkinsmedicine.org/provider/sairam-geethanath/2777486"

      - image:       "images/AS.png"
        team:        "Reconstruction"
        name:        "Dr. Ajay Sharma"
        url:         "https://scholar.google.com/citations?hl=en&user=rojRnpEAAAAJ"

      - image:       "images/DSS.png" 
        team:        "Reconstruction"
        name:        "Dr. Sasi Dinil Sankaralayam"
        url:         "https://scholar.google.com/citations?hl=en&user=84pWKyEAAAAJ"

      - image:       "images/JB.png"
        team:        "Console software"
        name:        "Dr. Jonathan Martin"
        url:         "https://scholar.google.com/citations?hl=en&user=HSuqP_MAAAAJ"

      - image:       "images/ZM.png"
        team:        "System Phantom"
        name:        "Dr. Zinia Mohanta"
        url:         "https://scholar.google.com/citations?hl=en&user=zmXHDTMAAAAJ"



    tier3:
      - logo:        "images/codethink_logo.svg"
        name:        "Codethink"
        url:         "https://www.codethink.co.uk/"
     
    anycont:
      - logo:        "images/InformaticsUni_transparent.gif"
        name:        "University of Edinburgh School of Informatics"
        url:         "http://www.ed.ac.uk/informatics"
     

  info:
    sections:
      - image:       "images/learn.png"
        imagealt:    "Learning during workshop"
        title:       "Learn"
        description: >
         Come, learn from luminaries in the field and work closely with mentors with practical experience building system components. If you are a beginner, this is a great opportunity to sign up for our quick starter sessions and learn from some of the best in the field.
      - image:       "images/build.png"
        imagealt:    "Building during workshop"
        title:       "Build"
        description: >
          We will be building a low-field MRI scanner from scratch. You will be working in teams to build the magnet, RF coils, gradient coils, data acquisition and reconstruction components of the system. Come, experience the thrill of building a real MRI scanner with your own hands!
      - image:       "images/scan.png"
        imagealt:    "Get-together after scanning"
        title:       "Scan"
        description: >
          We will be scanning with the MRI scanner that you built! You will be able to scan a phantom and see the results of your hard work. This is a unique opportunity to see how the components you built come together to form a complete MRI system and produce images.
  # Frequently asked questions.
  faq:
    - question:      "How much does it cost?"
      answer:        >
        Nothing. Attending this workshop is free.
    - question:      "Do I need to be a student to attend?"
      answer:        >
        No. Anyone over the age of 18 with an interest in or experiene with MRI can attend.
    - question:      "I'm a complete beginner. Can I still come?"
      answer:        >
        Absolutely! We especially encourage people that are new in the field to come along as this workshop is a great place to get started. [Drop us a message](mailto:sairamgeethanath@gmail.com) if you have any concerns.
    - question:      "Where is the event?"
      answer:        >
        The event is being hosted at [Johns Hopkins University School of Medicine](https://maps.app.goo.gl/XTnVxt5uJx6UEYAY6).
    - question:      "Do you offer travel reimbursement?"
      answer:        >
        Based on available funding, we expect to fund approximately 6 (graduate or doctoral) students.
    - question:      "Is there a code of conduct?"
      answer:        >
        We will be using the MLH code of conduct and will be enforcing it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question:      "Do I have to come with teammates?"
      answer:        >
        Team-forming sessions are being organized by the team mentors and will be ready before the workshop. Please feel free to participate to let them know your preferences.

  schedule:
    Saturday:
      - text:        "Start of registration"
        start:       "10:00"
        track:       "main"
      - text:        "Team forming session 1"
        start:       "10:30"
        end:         "11:00"
        track:       "main"
      - text:        "Opening ceremony"
        start:       "11.00"
        end:         "12:00"
        track:       "main"
      - text:        "Start hacking"
        start:       "12:00"
        track:       "main"
      - text:        "Team forming session 2"
        start:       "12:01"
        end:         "12:30"
        track:       "main"
      - text:        "Introduction to electronics workshop"
        start:       "12:00"
        end:         "13:00"
        track:       "ws"
      - text:        "Introduction to MiRo workshop"
        start:       "12.00"
        end:         "13.00"
        track:       "ws"
      - text:        "Lunch"
        start:       "13:00"
        end:         "14:00"
        track:       "main"
      - text:        "Introduction to Microbit workshop"
        start:       "14:00"
        end:         "15:00"
        track:       "ws"
      - text:        "GitHub workshop"
        start:       "15.00"
        end:         "16.00"
        track:       "ws"

      - text:        "Line follower workshop"
        start:       "15:30"
        end:         "17.00"
        track:       "ws"
      - text:        "FPGA workshop"
        start:       "17:00"
        end:         "18:00"
        track:       "ws"
      - text:        "Dinner"
        start:       "18:00"
        end:         "19:00"
        track:       "main"
      - text:        "Introduction to IoT workshop"
        start:       "19.00"
        end:         "20.00"
        track:       "ws"
    Sunday:
      - text:        "Midnight snack"
        start:       "00:00"
      - text:        "Breakfast"
        start:       "08:00"
        end:         "09:00"
      - text:        "Submissions due"
        start:       "12:00"
      - text:        "Lunch"
        start:       "12.00"
        end:         "13.00"
      - text:        "Demos"
        start:       "13:30"
        end:         "15:00"
      - text:        "Closing ceremony"
        start:       "15:30"
        end:         "16:30"

  # This is the message you'll receive once you've registered.
  register:
    message:         >
      Thanks for signing up!
      {::nomarkdown}<br />{:/}
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown:            kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
